fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        message:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\DiscussionMessageUser
                provider: ~
                finder: ~
            properties:
                id: ~
                creatorUser:
                    type: object
                    properties:
                        id: ~
                message:
                    type: object
                    properties:
                        id: ~
                        message: ~
                        sensitiveDataMessage: ~
                        fileMessages:
                            type: object
                            properties:
                                id: ~
                                name: ~
                                originalName: ~
                                mimeType: ~
                                sensitiveDataName: ~
                        user:
                            type: object
                            properties:
                                id: ~
                discussion:
                    type: object
                    properties:
                        id: ~
                        personOneNumberUnreadMessages: ~
                        personTwoNumberUnreadMessages: ~
                        personOne:
                            type: object
                            properties:
                                id: ~
                        personTwo:
                            type: object
                            properties:
                                id: ~
                        creatorUser:
                            type: object
                            properties:
                                id: ~
                        dateCreation:
                            type: date
                        dateModification:
                            type: date
                dateCreation:
                    type: date
                dateModification:
                    type: date

        discussion:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Discussion
                provider: ~
                finder: ~
            properties:
                id: ~
                personOneNumberUnreadMessages: ~
                personTwoNumberUnreadMessages: ~
                personOne:
                    type: object
                    properties:
                        id: ~
                        name: ~
                        firstName: ~
                personTwo:
                    type: object
                    properties:
                        id: ~
                        name: ~
                        firstName: ~
                creatorUser:
                    type: object
                    properties:
                        id: ~
                dateCreation:
                    type: date
                dateModification:
                    type: date


